import { Component, signal, Signal } from '@angular/core';
import { VinylRecord } from '../../models/product.model';

import { ProductCardComponent } from '../../components/product-card/product-card.component';

@Component({
  selector: 'app-products-list',
  imports: [ProductCardComponent],
  template: `
    <div class="grid grid-cols-4 gap-4">
      @for (record of vinylRecords(); track record.id) {
        <app-product-card [VinylRecord]="record"></app-product-card>
      }
    </div>
  `,
  styles: ``,
})
export class ProductsListComponent {
  vinylRecords: Signal<VinylRecord[]> = signal([
    {
      id: '0',
      title: 'Graduation',
      coverImage: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Graduation_%28album%29.jpg/220px-Graduation_%28album%29.jpg',
      artist: 'Kanye West',
      releaseYear: 2007,
      genre: 'Hip-Hop',
      recordLabel: 'Roc-A-Fella Records',
      format: 'Vinyl',
      trackList: [
        'Good Morning',
        'Champion',
        'Stronger',
        'I Wonder',
        'Good Life (feat. T-Pain)',
        'Can’t Tell Me Nothing',
        'Barry Bonds (feat. Lil Wayne)',
        'Drunk and Hot Girls (feat. Mos Def)',
        'Flashing Lights (feat. Dwele)',
        'Everything I Am',
        'The Glory',
        'Homecoming (feat. Chris Martin)',
        'Big Brother',
      ],
      price: 25.99,
      stock: 10,
    },
    {
      id: '1',
      title: 'Demon Days',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Gorillaz_Demon_Days.PNG/220px-Gorillaz_Demon_Days.PNG',
      artist: 'Gorillaz',
      releaseYear: 2005,
      genre: 'Alternative Rock',
      recordLabel: 'Parlophone',
      format: 'Vinyl',
      trackList: [
        'Intro',
        'Last Living Souls',
        'Kids with Guns',
        'O Green World',
        'Dirty Harry',
        'Feel Good Inc.',
        'El Mañana',
        'Every Planet We Reach Is Dead',
        'November Has Come',
        'All Alone',
        'White Light',
        'Dare',
        "Fire Coming Out of the Monkey's Head",
        "Don't Get Lost in Heaven",
        'Demon Days',
      ],
      price: 29.99,
      stock: 5,
    },
    {
      id: '2',
      title: 'Feedback',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/b/b6/Jurassic_5-Feedback.png',
      artist: 'Jurassic 5',
      releaseYear: 2006,
      genre: 'Hip-Hop',
      recordLabel: 'Interscope Records',
      format: 'Vinyl',
      trackList: [
        'Back 4 U',
        'Radio',
        'Brown Girl (Ft. Brick & Lace)',
        'Gotta Understand',
        'In the House',
        'Baby Please',
        'Work It Out (Ft. Dave Matthews Band)',
        'Where We At (Ft. Yasiin Bey)',
        'Get it Together',
        'Future Sound',
        'J Resume',
        'Red Hot',
        'Turn It Out',
        'End Up Like This',
        'Canto De Ossanha',
        'What’s Golden',
      ],
      price: 44.99,
      stock: 3,
    },
    {
      id: '3',
      title: 'MM..FOOD',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/Mmfood.jpg/220px-Mmfood.jpg',
      artist: 'MF DOOM',
      releaseYear: 2004,
      genre: 'Hip-Hop, Rap',
      recordLabel: 'Rhymesayers Entertainment',
      format: 'Vinyl',
      trackList: [
        'Beef Rapp',
        'Hoe Cakes',
        'Potholderz',
        'One Beer',
        'Deep Fried Frenz',
        'Poo-Putt Platter',
        'Fillet-O-Rapper',
        'Gumbo',
        'Fig Leaf Bi-Carbonate',
        'Kon Karne',
        'Guinnesses',
        'Kon Queso',
        'Rapp Snitch Knishes',
        'Vomitspit',
        'Kookies',
      ],
      price: 59.99,
      stock: 2,
    },
    {
      id: '4',
      title: 'To Pimp a Butterfly',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png/220px-Kendrick_Lamar_-_To_Pimp_a_Butterfly.png',
      artist: 'Kendrick Lamar',
      releaseYear: 2015,
      genre:
        'Alternative Hip-Hop',
      recordLabel:
        'Top Dawg Entertainment, Aftermath Entertainment, Interscope Records',
      format: 'Vinyl',
      trackList: [
        "Wesley's Theory",
        'For Free? (Interlude)',
        'King Kunta',
        'Institutionalized',
        'These Walls',
        'u',
        'Alright',
        'For Sale? (Interlude)',
        'Momma',
        'Hood Politics',
        'How Much a Dollar Cost',
        'Complexion (A Zulu Love)',
        'The Blacker the Berry',
        "You Ain't Gotta Lie (Momma Said)",
        'i',
        'Mortal Man',
      ],
      price: 59.99,
      stock: 0,
    },
    {
      id: 'death-certificate',
      title: 'Death Certificate',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/6/63/Ice_Cube-Death_Certificate_%28album_cover%29.jpg',
      artist: 'Ice Cube',
      releaseYear: 1991,
      genre: 'Gangsta Rap',
      recordLabel: 'Lench Mob Records',
      format: 'LP',
      trackList: [
        'The Funeral (Intro)',
        'The Wrong Nigga to Fuck Wit',
        'My Summer Vacation',
        "Steady Mobbin'",
        'Robin Lench (Interlude)',
        "Givin' Up the Nappy Dug Out",
        "Look Who's Burnin'",
        'A Bird in the Hand',
        "Man's Best Friend",
        'Alive on Arrival',
        'Death',
        'The Birth',
        'I Wanna Kill Sam',
        "Horny Lil' Devil",
        'Black Korea',
        'True to the Game',
        'Color Blind',
        'Doing Dumb Shit',
        'Us',
        'No Vaseline',
        'Only One Me',
        'Good Cop, Bad Cop',
        'Dominate the Weak',
        'Trying To Maintain',
      ],
      price: 49.99,
      stock: 5,
    },
    {
      id: '6',
      title: 'Every Hero Needs a Villain',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Czarface_Every_Hero_Needs_a_Villain.jpg/220px-Czarface_Every_Hero_Needs_a_Villain.jpg',
      artist: 'Czarface',
      releaseYear: 2015,
      genre: 'Hip-Hop',
      recordLabel: 'Mello Music Group',
      format: 'Vinyl',
      trackList: [
        'Don the Armor',
        'Czartacus',
        'Lumberjack Match',
        'Nightcrawler (featuring Method Man)',
        'World Premier (featuring Large Professor)',
        'The Great (Czar Guitar)',
        'Red Alert',
        'Junkyard Dogs (featuring JuJu)',
        'Sgt. Slaughter',
        'When Gods Go Mad (featuring GZA)',
        'Ka-Bang! (featuring MF Doom)',
        'Deadly Class (featuring Meyhem Lauren)',
        'Escape from Czarkham Asylum',
        'Sinister',
        'Good Villains Go Last (featuring R.A. the Rugged Man)',
        "Deviatin' Septums (Digital Exclusive)",
        'Sinister (Revenge of Yorgo Remix) (Digital Exclusive)',
      ],
      price: 59.99,
      stock: 1,
    },
    {
      id: '7',
      title: 'Social Cues',
      coverImage:
        'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Cage_the_Elephant_Social_Cues.jpg/220px-Cage_the_Elephant_Social_Cues.jpg',
      artist: 'Cage the Elephant',
      releaseYear: 2019,
      genre: 'Alternative Rock',
      recordLabel: 'RCA Records',
      format: 'Vinyl',
      trackList: [
        'Broken Boy',
        'Social Cues',
        'Black Madonna',
        'Night Running',
        'Skin and Bones',
        'Ready to Let Go',
        'House of Glass',
        'Love’s the Only Way',
        'The War is Over',
        'Dance Dance',
        'What I’m Becoming',
        'Tokyo Smoke',
        'Goodbye',
      ],
      price: 35.99,
      stock: 0,
    },
  ]);
}
